export const browserCoreExamples = [
  "hex browser status",
  "hex browser start",
  "hex browser stop",
  "hex browser tabs",
  "hex browser open https://example.com",
  "hex browser focus abcd1234",
  "hex browser close abcd1234",
  "hex browser screenshot",
  "hex browser screenshot --full-page",
  "hex browser screenshot --ref 12",
  "hex browser snapshot",
  "hex browser snapshot --format aria --limit 200",
  "hex browser snapshot --efficient",
  "hex browser snapshot --labels",
];

export const browserActionExamples = [
  "hex browser navigate https://example.com",
  "hex browser resize 1280 720",
  "hex browser click 12 --double",
  'hex browser type 23 "hello" --submit',
  "hex browser press Enter",
  "hex browser hover 44",
  "hex browser drag 10 11",
  "hex browser select 9 OptionA OptionB",
  "hex browser upload /tmp/file.pdf",
  'hex browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "hex browser dialog --accept",
  'hex browser wait --text "Done"',
  "hex browser evaluate --fn '(el) => el.textContent' --ref 7",
  "hex browser console --level error",
  "hex browser pdf",
];
